#!/bin/sh

#LAUNCHERS
run sxhkd -c ~/.config/bspwm/sxhkdrc &
run ulauncher &
$HOME/.config/bspwm/autostart.sh

#BSPWM configuration
bspc config border_radius        50
bspc config border_width         4
bspc config window_gap           0 #k
bspc config top_padding          30
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config single_monocle       false
#bspc config click_to_focus       true
bspc config split_ratio          0.65
bspc config borderless_monocle   true
bspc config gapless_monocle      true
#bspc config focus_by_distance    true
bspc config focus_follows_pointer true
#bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true

#BSPWM coloring
bspc config normal_border_color		"#202020"
bspc config active_border_color		"#3f3f3f"
bspc config focused_border_color	"#404040"
bspc config presel_feedback_color	"#5e81ac"
#bspc config urgent_border_color 	"#dd2727"

#Single monitor
bspc monitor -d 1 2 3 4 5 6 7

#Floating applications
bspc rule -a Arandr state=floating
#bspc rule -a Font-manager state=floating
bspc rule -a Galculator state=floating
bspc rule -a Gpick state=floating sticky=on
bspc rule -a Nitrogen state=floating
bspc rule -a Oblogout state=floating
#Tiled applications
bspc rule -a Gnome-disks state=tiled
bspc rule -a Xfce4-settings-manager state=tiled

nitrogen --restore & 
